### ISSUE TITLE
Create file structure for repo

### ISSUE THREAD

**Issue by dstorie80** [Davidtruong02/The_Prudent_Pantry_App#1]
Create the file structure in the repo by following MVC file structure (config, controllers/api], models, public, utils, and views folder.

**Comment by akayer19** [comment]
Action complete. 

'git clone https://github.com/Davidtruong02/The_Prudent_Pantry_App.git'

then:

'cd prudent-pantry'

then:

'npm install express sequelize mysql2 express-handlebars dotenv passport passport-local bcrypt tailwindcss'
